### ISSUE TITLE
Peer to Peer code review Week 5 Day 5

### ISSUE THREAD

**Issue by mirouhml** [Bavon101/flash_comicon#4]
Hello Bavon, your website and code both look good but there are just a few minor suggestions we have for you:
- It would be better if you put the top bar (the one with the social media links) in the header as a nav bar.
- It would also be better if the content of the footer are justified to the center, it would make it look good.

**Comment by Bavon101** [comment]
@mirouhml Thank you for catching these issues, I'll work on them 🐱‍🏍.
